export { bakeSegmentEdits } from './bake.js';
export type { BakeResult } from './report.js';
export { BakeReport } from './report.js';
export { textEmitStrategies } from './text.js';
export type { ITextEmitStrategy, SegmentEmitContext } from './text.js';
export { rebuild } from './splice.js';
export type { Splice } from './splice.js';
export { stdFontFor } from './fonts.js';
export { hexToRg, rawFillToRgb, isWhiteFill } from './color.js';
export { tokenizeContentStream } from './tokenizer.js';
export type { OpRecord, Token } from './tokenizer.js';
export { walkTextOps, walkContent } from './textWalk.js';
export type { ShowOp, Matrix, XObjectOp, ContentWalk, FillRectOp } from './textWalk.js';
export { hideHighlightAnnotations } from './highlights.js';
export { parseToUnicode } from './toUnicode.js';
export type { ReverseEncoder } from './toUnicode.js';
export { addFormField, insertImage, addText, addWatermark, addHeaderFooter, addHighlight, addLink, removeLink, setFieldOptions, addRadioOption, FIELD_DEFAULT_SIZE } from './createNodes.js';
export type { NewFieldSpec, NewImageSpec, NewTextSpec } from './createNodes.js';
